version: '3.8'

services:
    photon:
        build: 
            context: photon
            dockerfile: Dockerfile_new
        ports:
            - "2322:2322"
        networks:
            - backend
        volumes:
            - photon_data:/data/photon_data
    proxy:
        build: 
            context: proxy
            dockerfile: Dockerfile
            args: 
                cert: certs/cert.pem
                cert-key: certs/privkey.pem
                rate-limit: 100
                rate-reset: 60
        ports:
            - "443:443"
        networks:
            - backend
    
networks:
    backend:
        driver: bridge

volumes:
    photon_data:
        driver: local