version: '3.8'

services:
    proxy:
        build: 
            context: proxy
            dockerfile: Dockerfile
        ports:
            - "8081:443"
        networks:
            - backend
        depends_on: 
            - redis
            - photon
    photon:
        build: 
            context: photon
            dockerfile: Dockerfile
        ports:
            - "2322:2322"
        networks:
            - backend
        volumes:
            - photon_data:/data
    redis:
        image: redis:latest
        restart: unless-stopped
        networks:
            - backend
    
networks:
    backend:
        driver: bridge

volumes:
    photon_data:
        driver: local